### ISSUE TITLE
VS Code integration utterly fails.

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#122]
Attempted support for colourisation is in `plugins/vscode` directory.

**Comment by CaviarChen** [comment]
Wow! There are so many exciting things going on with Wybe.
Sorry that I don't have time to contribute (at least recently), but I'm here to share some ideas. I actually tried to build a vscode plugin for Wybe before and failed.

In short, I think we could try to build a language server directly.
Here are some reasons:
1) rewrite the parser in Textmate is annoying and I don't think the wybe syntax is stable now (correct me if wrong) so we need to maintain two parsers.
2) Textmate syntax is not powerful enough and we need to switch to language server sooner or later.
3) We can build the language server in Haskell so we can reuse the existing parser. Haskell has a pretty good lsp implementation: https://github.com/haskell/lsp
For highlighting, all we need is a function that takes a wybe source file and returns a list (or tree) of symbols with their range in the text and types (supporting Document Symbols Request: https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_documentSymbol). 

Potential problems:
1) There might be a performance issue since our native implementation will analyze the whole file every time we change it.
2) Might be hard to support recovering from syntax errors and producing a resilient parse tree.

**Comment by pschachte** [comment]
Great to hear from you, Zed.

I was really just trying to get colourisation working.  I was hoping I could put in an hour or two to get at least comments coloured, and maybe proc names and even variable assignments.  I spent 4 or 5 hours and nothing worked beyond recognising that a filename ending in .wybe was a Wybe file.  But somehow when you type the open parenthesis after a proc name, it shifts the whole line to the left margin.

I suppose a language server is a good idea in the long run, as it has much more potential, such as highlighting type or other semantic errors.  And you're right, the syntax is not stable yet, and being able to use the same parser for the language server and the compiler would be good design.  On the other hand, it has the problem that a syntax error in the middle of the file will mess up everything that comes later.  But the biggest problem is that it looks like a lot of work, and it's just not a very high enough priority.

**Comment by CaviarChen** [comment]
I think the one I made works with comments and can highlight keywords (exact match).
I'll try to find it and create a PR later (hopefully today, or at least by the end of this week).

**Comment by pschachte** [comment]
That would be great, thank you!

**Comment by CaviarChen** [comment]
I closed the previous pull request.
I implemented a version and put it here: https://github.com/CaviarChen/vscode-wybe
The plugin is publised to Visual Studio Marketplace, you can find it here: https://marketplace.visualstudio.com/items?itemName=wybe.vscode-wybe
Or just search "wybe" in vscode.

I am currently the owner of that repo and also the publisher "Wybe" on Visual Studio Marketplace.
Hope that fine to you, I am happy to transfer these to you.

**Comment by pschachte** [comment]
Hi Zed,

It works great, thanks for setting that up!

**Comment by pschachte** [comment]
Zed's VS Code Wybe plugin, hosted by VS Code, works fine.
