### ISSUE TITLE
wybe compiler give internal error when compiling helloworld.wybe

### ISSUE THREAD

**Issue by 09milk** [pschachte/wybe#13]
What I tried to do:
```
% cat hello_world.wybe
!println("Hello, World!")

% wybemk hello_world
Internal error: Invalid Wybe object file /usr/local/lib/wybe/wybe.o:  module data missing
CallStack (from HasCallStack):
  error, called at src/AST.hs:2784:17 in main:AST
```
Seems like the function `loadModuleFromObjFile` failed when loading the standard library: 
https://github.com/pschachte/wybe/blob/6350c56a189209188b49d37c78f03871ac611931/src/Builder.hs#L492

All of the above is done under Ubuntu 18.04.2

**Comment by CaviarChen** [comment]
Temporary workaround: 
Add sudo, for example: `sudo wybemk hello_world`

The issue here is that the global installed copy of wybe lib object file `/usr/local/lib/wybe/wybe.o` is read only. The code that extracting module uses `objcopy --dump-section` which requires write permission. That is odd. I'll fix it.

For future work, this means we can't store optimization decisions into object file directly, right? @pschachte
