### ISSUE TITLE
Loops can bind variables that are not guaranteed to be bound 

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#191]
The following example program should report an error by the compiler, as we cannot guarantee that the variable `i` will be bound after the end of the loop.

```
?ls = []
do {
    while [?i | ?ls] = ls
}
!println(i:int)
```

Instead, the compiler succeeds and the program will print "0", as `i` is undefined at this point.

**Comment by jimbxb** [comment]
This looks to be related to #173. In general I think there's something off with bindings in mode checking. 

`while foo(a, ?b)` gets flattened to `if { foo(a, ?b) :: pass | else :: break }`. To my understanding, an `if`-`else` block should only bind variables off the variables are bound in both breaches. Flattening a `while` like this would preclude mode checking from binding `b` in the rest of the loop because the `else` branch doesn't bind `b`. 

We could either choose to flatten `while` differently, and ensure that somehow `b` is bound accordingly. 

I think we might need to do something a little different, however, and keep the loop-control statements (`while`, `unless`, etc) through type checking and remove them in either mode checking or unbranching.

**Comment by pschachte** [comment]
You're almost right:  conditionals should only be considered to bind variables that are definitely bound in all branches *that could possibly return*.  But `break` and `next` statements are terminal, and can't return (this is part of the reason I added the Terminal determinism).  So after a statement like
```
if {test... :: ?x = 1
   | else :: break
}
```
we can know that `x` is bound, because if we don't assign `x`, we must have executed the `break`, in which case we wouldn't reach the statement after the conditional.

The bug was just that, after carefully computing the set of variables defined at the loop exit (ie, at all breaks), I forgot to install it as the set of defined variables after the loop.  I also wasn't resetting the set of variables defined at all loop exits when I started processing a loop, which messed up nested loops.  So there were two bugs there.
