### ISSUE TITLE
Types of type constrained manifest constants are ingored

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#229]
Example:
```
println("hello":int)
println(c"hello":string)
println(1.0:string)
```

This code compiles, though should probably be a type error, as the underlying constant does not have a compatible type with the constrained type. 

Note: some cases of this can be useful for shorter expressions, such as:
```
type my_int is 32 bit signed {}

?x = 0:my_int
# instead of 
?x = foreign lpvm cast(0):my_int
```

**Comment by pschachte** [comment]
Ah, now I remember why type constraints are ignored for manifest constants.  The problem is that integer constants can be either ints or counts.  We should probably add other signed and unsigned fixed and variable bit-width integer types to the library, too, and allow integer manifest constants of those types, too.  So my short-term answer was not to type check manifest constants.  A longer term answer is to parse integers of any bit-width as some special integer type, and allow integer types to define type coercion from that type (and any integer type of no fewer bits) to itself.

**Comment by jimbxb** [comment]
This PR should allow for constraints to be used in their current capacity, except it makes obviously bad constraints illegal (`1:string`). Currently to instantiate a `count`, one must use `0:count`, as integer constants default to the `int` type.

Obviously an approach like #100 is better. This PR only attempts to make some obviously wrong constraints illegal
