### ISSUE TITLE
Better data types needed to make good use of the Haskell's type system

### ISSUE THREAD

**Issue by CaviarChen** [pschachte/wybe#28]
For example, we store LPVM instructions using this data structure which is very error-prone.
https://github.com/pschachte/wybe/blob/f68d0f50d7df8a262886b8666d3c94b60631cd61/src/AST.hs#L1948

If we add an incompatible change to the LPVM instructions. It won't case a compile error and in some cases it won't even cause a runtime error.

Most of the current codes just match on the strings and make assumptions about the length of list etc, and the compiler can't verify it.

**Comment by pschachte** [comment]
I believe these are now checked by the Wybe type checker (in Types.hs), rather than in the Haskell type system.  This is a trade-off designed to avoid tying Wybe too closely to LLVM, and to keep the Wybe foreign interface as simple as possible.

Please create a new issue if any specific example of an erroneous LLVM instruction not detected by the Wybe type checker is found.
