### ISSUE TITLE
Syntax error with top-level disjunction

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#374]
For some reason, a disjunction at the top-level causes a syntax error. The following is a simple case that is failing to parse:

```
pass | !error("oops")
```
```
Error detected during loading module: test
test.wybe:1:6: Syntax error: unexpected operator symbol |
expecting simple expression or end of input
```

Similarly,
```
1 = 1 | !error("oops")
```
```
Error detected during loading module: test
test.wybe:1:7: Syntax error: unexpected operator symbol |
expecting end of input
```

This does not occur inside a procedure definition, from what I tested. This works as expected:
```
def {impure, inline} foo {
    fail | !error("oops")
}
!foo
```
```
❯ ./wybemk ./test && ./test
test:2:13: oops
```

**Comment by jimbxb** [comment]
To hazard a guess at the cause of this, I suspect there is a precedence issue at the top-level. `|` has precedence `-3`, but a top-level statement has that of `0`

**Comment by pschachte** [comment]
I'm not sure that this can be fixed.  The `|` operator is defined to bind looser than `;` (or newline), and I think that's the right thing to do.  That's certainly how you want it to behave in a conditional.  So surrounding braces are needed to delimit the compound `|` statement.  But at the top level of a file, you write individual statements, and I think it would be confusing to do otherwise.  For example, suppose you write:
```
do_something | do_something_else

def another_thing(...) { ... }

one_more_thing
```
Wouldn't you be surprised that `one_more_thing` only gets executed if `do_something` fails?  Wouldn't it be better to force the programmer to write this?
```
{ do_something | do_something_else }
...
```

Marking as invalid for now; feel free to reopen and remove that flag if you see a solution to this problem.

**Comment by jimbxb** [comment]
Yeah, I have thought about this a bit since I raised it and I understand now why it's a syntax error. I think the way it is works fine.
