### ISSUE TITLE
Allow use of a `!variable` as an input to a proc, combined with omission of the sole ouput

### ISSUE THREAD

**Issue by pschachte** [pschachte/wybe#394]
The idea here is to use a function as a proc in a pseudo-destructive way.  For example, you could write

```
sort(!list)
```

as syntactic sugar for `sort(list, ?list)` or equivalently `?list = sort(list)`, sorting `list` and putting the result back in `list`.

Similarly,

```
!x*2
```

(as a statement) would double `x`.  This would obviate all the `+=`, `-=`, etc. statements, and be far more general.

**Comment by jimbxb** [comment]
Just for clarification: all arguments except for this `!` should be inputs, right? 

Upon reading this, I first thought that the idea was to transform a `!x` argument into a pair `x, ?x`, which would work well for the `sort` example, but not for the `*`. This is because the call would be much like `` `*`(x, ?x, 2)``, which sets `?x = 2/x`.

**Comment by pschachte** [comment]
I don't think we need to be quite that strict, although that would probably be the common case.  It should be OK to have other in-out arguments, just no other outputs.

**Comment by pschachte** [comment]
To clarify, a `!` argument passed where an input is expected would be treated as just an input of that type, as long as there's also an output parameter of that type which is omitted in the call.  Eg, with a proc `foo(int, int, int, ?int, int)`, a call `foo(x, !y, z, w)` would be interpreted as `foo(x, y, z, ?y, w)`.
