### ISSUE TITLE
Conflict when importing resources with the same name from different modules

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#414]
`a.wybe`
```
pub resource res:int  = 42
```
`b.wybe`
```
pub resource res:char = 'c'
```
`c.wybe`
```
use a, b
?c = 0
```
Compiling `c.wybe` would produce the following error message:
```
Error detected during type checking of module(s) c
Type/flow error in definition of module top-level code, resource b.res
```
The `Types` log shows an attempt to unify `a.res` and `b.res`. It seems Wybe is trying to define a local variable `res`, which is ambiguous.
```
Types: **** Validating parameter types in module c
Types: Validating def of 
Types: **** Re-exiting module c
Types: **** Type checking modules c
Types: **** Strongly connected components:
Types:     c.
Types: Type checking non-recursive proc c.
Types: ** Type checking decl of proc 
Types: found 1 definition(s)
Types: Type checking module top-level code
Types: ** Type checking module top-level code: Typing {}; {} (with no errors)
Types:    with resources: fromList [!a.res,!b.res,!wybe.io.io]
Types:    containing calls: 
Types:         =(?c @c:2:2, 0 @c:2:6)
Types:    with assigned vars: fromList ["c","io","res"]
Types: Recording parameter types: 
Types: Recording resource types: !a.res, !b.res, !wybe.io.io
Types: Unifying types wybe.int (-> wybe.int) and any (-> any)
Types:   Unification yields wybe.int
Types: Variable res type constrained to wybe.int
Types: Unifying types wybe.char (-> wybe.char) and wybe.int (-> wybe.int)
Types: Recording error(s): [Error Nothing: Type/flow error in definition of module top-level code, resource b.res]
Types:   Unification yields XXX
Types: Variable res type constrained to XXX
Types: Unifying types wybe.phantom (-> wybe.phantom) and any (-> any)
Types:   Unification yields wybe.phantom
Types: Variable io type constrained to wybe.phantom
Types: ** New definition of :
Types: 
Types: module top-level code > public {semipure} (0 calls)
Types: 4: () use !a.res, !b.res, !wybe.io.io:
Types:     =(?c @c:2:2, 0 @c:2:6)
```

**Comment by jimbxb** [comment]
This issue is caused by resources being referred to by their unqualified name. This has been a long standing "issue" and there is an `XXX` in the code regarding it.

To fix, we'd need to support module qualified resource names, `module.resource`. Parsing these will look ambiguous with a call to an argumentless function of the same name, but there shouldn't be too many cases where this is actually ambiguous, and an error would be appropriate.

Once we can figure out if something is a resource, we'd need to module qualify any references to these resources in the code. This can be done in a pass before type checking (probably in normalisation). Each variable that looks like a resource that's in scope can be normalised to a reference to said resource, and if there is more than one said resource, we must throw an error.

Then type checking just needs to know how to handle resources alongside variables, which should be a matter of adding a separate typing map, or allowing resources with variables in the current maps.
