### ISSUE TITLE
Public resources in a submodule are not exported correctly to the supermodule

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#415]
`c.wybe`
```
module a {
    pub resource res:int = 42
}
?c = 0
```
Compiling `c.wybe` produces the following error message:
```
Error detected during type checking of module(s)
Resource c.a.res not in scope at call to module top-level code
```
The dump (excluding `command_line`) right before the type checking fails.
```
AFTER FLATTENING:
 Module 
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : 
  imports         : use c
                    use command_line
                    use wybe
                    use wybe.array
                    use wybe.bool
                    use wybe.c_string
                    use wybe.char
                    use wybe.comparison
                    use wybe.control
                    use wybe.count
                    use wybe.float
                    use wybe.int
                    use wybe.io
                    use wybe.list
                    use wybe.machine_word
                    use wybe.memory_management
                    use wybe.phantom
                    use wybe.predicate
                    use wybe.range
                    use wybe.string
  resources       : 
  procs           : 

module top-level code > {terminal,impure} (0 calls)
0: () use command_line.argc, command_line.argv, ?command_line.exit_code:
    use command_line.arguments, command_line.command, wybe.io.io in
        !wybe.memory_management.
        !wybe.io.
        !command_line.
        !c.
        foreign c {semipure,terminal} exit(exit_code:wybe.int)
    }

LLVM code       : None

--------------------------------------------------
 Module c
  representation  : (not a type)
  public submods  : 
  public resources: 
  public procs    : c.<0>
  imports         : use c.a
                    use command_line
                    use wybe
  resources       : 
  submodules      : c.a
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: c.<0>
()<{}; {}; {}>:
  AliasPairs: []
  InterestingCallProperties: []

LLVM code       : None

--------------------------------------------------
 Module c.a
  representation  : (not a type)
  public submods  : 
  public resources: res: c.a.res
  public procs    : c.a.<0>
  imports         : use c
                    use wybe
  resources       : res: fromList [(c.a.res,wybe.int = 42 @c:2:28 @c:2:9)]
  procs           : 

module top-level code > public {inline,semipure} (0 calls)
0: c.a.<0>
()<{}; {<<c.a.res>>}; {}>:
  AliasPairs: []
  InterestingCallProperties: []
    foreign lpvm store(42:wybe.int, <<c.a.res>>:wybe.int) @c:2:9

LLVM code       : None

...

Types: Matching types [] with {semipure} c.<0>() use res, io, ?res, ?io
Types: Type-correct modes   : [({semipure} c.<0>() use res, io, ?res, ?io,Typing {argc::wybe.int, arguments::wybe.array(wybe.c_string), argv::wybe.array.raw_array, command::wybe.c_string, exit_code::wybe.int, io::wybe.phantom}; {} (with no errors))]
Types: Possible mode matches: [({semipure} c.<0>() use res, io, ?res, ?io,Typing {argc::wybe.int, arguments::wybe.array(wybe.c_string), argv::wybe.array.raw_array, command::wybe.c_string, exit_code::wybe.int, io::wybe.phantom}; {} (with no errors))]
Types: Exact mode matches: [({semipure} c.<0>() use res, io, ?res, ?io,Typing {argc::wybe.int, arguments::wybe.array(wybe.c_string), argv::wybe.array.raw_array, command::wybe.c_string, exit_code::wybe.int, io::wybe.phantom}; {} (with no errors))]
Types: Recording error(s): [Error Nothing: Resource c.a.res not in scope at call to module top-level code]
Types: Finalising call    :  {!c.<0>}
Types: Input resources    :  {c.a.res, wybe.io.io}
Types: Output resources   :  {c.a.res, wybe.io.io}
Types: Specials in call   :  {}
Types: Available vars     :  {"argc", "arguments", "argv", "command", "exit_code", "io"}
Types: Available resources:  {command_line.argc, command_line.arguments, command_line.argv, command_line.command, command_line.exit_code, wybe.io.io}
Types: Generated special stmts = []
Types: New instr = {!c.<0>}
Types: Generated extra stmts = []
Types: Mode check end of Terminal proc module top-level code
Types: Now assigned = impure normal (total) computation binding {argc, arguments, argv, command, exit_code, io, res}, break set = Everything, with resources {command_line.argc, command_line.arguments, command_line.argv, command_line.command, command_line.exit_code, wybe.io.io}
```

**Comment by jimbxb** [comment]
This looks like the error message is missing the proc name, so it must be in the module, top-level code. Can you add a dump for those?

**Comment by wnats** [comment]
Updated the top comment.

**Comment by jimbxb** [comment]
Well that's odd. I can't see a call to some main proc where `a.res` needs to be in scope. The only reference to it is in the `a` main proc, and that flows out.

**Comment by wnats** [comment]
My bad, I used an outdated `wybemk` (before the adding more details to logs/error messages commit) to produce the error message. I have updated the error message with the updated one.

**Comment by wnats** [comment]
> I think also, there should be a call `!c.a.` that's missing? Maybe adding in a call to `!c.a.` before `!c.` in the executable main would fix this?

I think so too.

I'm also unsure why `c.<0>` uses `!res`.

**Comment by jimbxb** [comment]
No, it should be `!res` in `c.`, as the resource must be initialised before it's called. And it will be initialised, after the call to `c.a.` in the exe main

**Comment by pschachte** [comment]
I suspect this bug has always been there.  I think it's because submodule initialisations are not called.  The question is:   is the right solution for the main to directly call submodule initialisations, or is the right solution for parent module's initialisations to call their submodules' initialisations?  At the moment I'm leaning toward the latter, as it seems neater.

**Comment by jimbxb** [comment]
On one hand, the executable main calling the submodule's initialisation code makes sense -- they are just like any other module, so why treat their initialisation differently?

One issue I see with that, though, is when a submodule is private. The executable main won't "see" the top-level code, so we couldn't call it there. 

Perhaps in the parent module makes more sense then. That would also mean the parent module "initialises" any submodule's resources.

**Comment by pschachte** [comment]
I think it'll just make executable generation a bit simpler.  The only thing I'm worried about now is if one module imports `m` and another directly imports `m.s`, then how do we avoid the initialisation of `m.s` getting invoked twice?  Actually, I think that's a problem either way.  Grumble.

**Comment by jimbxb** [comment]
I don't think that's a problem. It's not a problem now if we import the same module in two imported modules, as the executable main is responsible for calling the top-level code. 

If the executable main is only responsible then for calling the top-level code of a file-level module `m` (for lack of a better term), and `m` is responsible for `m` for `m.s`, `m.s` is only called once.

**Comment by jimbxb** [comment]
Another question: if we import `m.s` explicitly, and don't import `m` alone, should the top-level code of `m` be ran?

Also, when do we call the top-level code of `m.s`. I think the right spot is after the `resource res:foo = bar` code is called, but before the actual top-level code of `m`, as `m.s` may rely on the resource of `m` being initialised to some value

**Comment by pschachte** [comment]
Submodule semantics are that submodules have access to everything in the parent module, and the parent module has access to everything exported from their submodules.  So modules and their submodules are each allowed to use each other's resources, including to initialise their own resources.  There's a problem here.  In a comment on another bug related to module initialisation, I suggested that mutually dependent modules should not be able to use each other's resources in their initialisations.  I think that needs to be the policy, because we can't know a priori which to initialise first.  But in the special case of submodules, we can establish a policy that says whose initialisation code can depend upon whose.  Since submodules have more control of visibility, and are meant to provide nuggets of functionality to their parents, it seems better to me to perform submodule initialisations first, implying that parent modules' initialisations can depend on their submodules' initialisations and not vice versa.  And I think that answers your question in the negative:  it's not necessary to run toplevel code of parent modules if only their submodules are used.

Now I'm wondering whether it was a good idea to say that submodules have access to everything in their parents.  Maybe they shouldn't have access to anything from their parents, making the dependency one-way.

**Comment by pschachte** [comment]
Nup, submodules need access to sibling modules and their exports, because some of them are types with their constructors.  So much for that fix.

**Comment by jimbxb** [comment]
I'm still a fan of the idea of having a separate proc that initialises resources to their declared values. that way, we can more easily interleave (sub)module's resource initialisation, which is what I think we'd want to do with siblings here.

**Comment by pschachte** [comment]
By "interleave", do you mean execute all submodules' resource initialisations, then execute all their other initialisations?  Or is the idea that all resources in the program are initialised first, in module dependency order, and then all module top-level code, in dependency order?  I'm not sure exactly what you mean.

**Comment by jimbxb** [comment]
If we're going to have `m` execute the top-level code for `m.s`, then we should also initialise the resources for `m.s` when we initialise the resources for `m` too. 

With the resource initialisation code, I think it makes most sense to initialise the resources of `m.s` inside the resource initialisation of `m`. It would be something to the effect of

```
# in executable
def main() {
    !m.#resources
    !m.
}

def m.#resources use ?m.res, ?m.s.res {
    !m.s.#resources
    ?m.res = ...
}

def m.s.#resources use ?m.s.res {
     ?m.s.res = ...
}

def m. use !m.res, !m.s.res {
    !m.s.
    # top-level code in m
}

def m.s. use !m.res, !m.s.res {
    # top-level code in m.s
}
```

**Comment by pschachte** [comment]
Hi James,

 I'm working on the fix for this.  Actually, this bug as reported is already fixed in an earlier merge, but I'm not marking it fixed because you still can't build an executable if a submodule declares an initialised resource that's actually used.

I realised that you're right, resource initialisation needs to be moved out of module top-level code, because with the current scheme, mutually dependent modules (which includes modules and their submodules) can't rely on resources being initialised when their top-level code runs.

I've decided on a slightly simpler two-phase model than discussed above.  Rather than create two initialisation procs per module, I have the main executable proc directly initialise all the resources.  The approach is to initialise modules by SCC, in topological order (main executable module last).  Each SCC is initialised in two phases:  first all resource initialisations for the SCC are executed directly by the main code, then each initialisation proc in the SCC is executed in turn.  This ensures that all visible resources for each module are initialised before its top-level code runs.  I sort each module SCC in reverse alphabetical order, forcing resources in submodules to be initialised before resources in their parents, and likewise for module top-level code.  This also means that the module top-level code for a module's dependencies (excluding mutual dependencies), is executed before the module's resources are initialised, so resource initialisations can depend on the initialisation code in the modules it uses, as long as they're not mutually dependent.

This is all implemented in the `subresources` branch.  It seems to generate the right code for all the modules, including the generated main, and it passes the whole test suite, except for some reason, if the initialised resource is in a submodule, the code won't link, whereas if the initialised resource is not in a submodule, it works fine.  For example,
```
pub resource res:int = 42
!println("res = $res")
```
compiles and runs just fine, but
```
module a {
    pub resource res:int = 42
}
!println("res = $res")
```
compiles just fine, generating sensible looking LPVM and LLVM code, but won't link, getting this error from the linker:
```
ld: Undefined symbols:
  _resource#subresource.a.res, referenced from:
      _main in tmpMain.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm not sure why this is happening.  The main module does generate a line
```
@"resource#subresource.a.res" = external   global i64
```
in the LLVM code, and the `subresources.a` module does generate:
```
@"resource#subresource.a.res" =    global i64 undef
```
the main proc does call
```
store  i64 42, i64* @"resource#subresource.a.res"
```
right after `gc_init()`, and the top-level code for `subresource` does execute
```
%0 = load  i64, i64* @"resource#subresource.a.res"
```
before doing anything else.  It all looks correct to me.

So any idea what could be causing the linker to blow up?

**Comment by jimbxb** [comment]
Hi Peter,

The new scheme seems sensible enough, with having `main` do the initial initialisation. 

I'm not going to pretend to know how a linker works, but as it's only when submodules are in the picture, I want to say there must be some issue with symbols in those modules. 

I forget how the object files are created: is it one object file per source file, or one object file per module/type (including sub modules). 

If it's the latter, then perhaps when constructing those files, the resources get "lost" in the process of creating them. I'm curious though why functions defined in sub modules work fine, and if (string) constants, which are compiled down into globals, much like resources also work fine.

If I get some time I'll try to have a deeper look at the issue, but I'm a little short right now.
