### ISSUE TITLE
Add an `error` function returning `any` type

### ISSUE THREAD

**Issue by wnats** [pschachte/wybe#434]
This is would resemble Haskell's `error` which matches with any type. One motivation would be in conditional/case _expressions_ where we have exhaustively list all possible outcomes but the compiler still requires an `else` branch. For instance, the following example in `WYBE.md` would work:
https://github.com/pschachte/wybe/blob/29ae3cbf675fde812066477da17ca45c3a277ad6/WYBE.md?plain=1#L1169-L1176

One primary challenge would be handling the special resource `call_source_location` which the current `error` _statement_ uses.

Although of course, a better long-term solution would be #19.

**Comment by pschachte** [comment]
This shouldn't be necessary; the `terminal` determinism should take care of it.  The determinism of `error` is `terminal`, which is even more deterministic than deterministic, in that deterministic code is only considered to generate the variables it binds, while `terminal` code generates all possible variables.  Your code example code should work; if not, please report it as a bug.

Making `error` a built-in is not a great solution to the problem, because procedures you write yourself wouldn't have the benefit of being built-in, so they would still have whatever problems making `error` a built-in is meant to work around.  This idea is beautifully explained in one of the best talks I've ever seen:  [Growing a Language](https://www.youtube.com/watch?v=_ahvzDzKdB0).  That's what motivated the introduction of the `terminal` determinism (Mercury has a similar determinism).

**Comment by wnats** [comment]
@pschachte The code example does not work since `error` currently is a statement, not an expression (#433)

**Comment by jimbxb** [comment]
I believe the following could suffice:

```
def error(msg:string, ?a:T) {
    !error(msg)
    foreign lpvm cast(0, a)
}
```
