### ISSUE TITLE
The Scanner doesn't handle float literal properly.

### ISSUE THREAD

**Issue by CaviarChen** [pschachte/wybe#56]
err.wybe
```
?x = 0.01
!println(x)
```

output:
```
Syntax Error: "./err.wybe" (line 1, column 7):
unexpected TokSymbol "." "./err.wybe" (line 1, column 7)
expecting simple expression terms, relational expressions or end of input
```

I believe the wrong part is here, a number that stars with 0 is considered to be octal.
https://github.com/pschachte/wybe/blob/db7242e5df66728eab1bdee5d6baa6a8dca8aa9b/src/Scanner.hs#L113-L115

Also, based on the [current document](https://github.com/pschachte/wybe/blob/master/WYBE.md#constants). For the scientific notation of a float, the "order of magnitude" part can't be negative. That's a bit odd.

**Comment by CaviarChen** [comment]
It also can't handle negative float, such as:
`?x = -12.1`

**Comment by pschachte** [comment]
I fixed the problem scanning numbers beginning with 0, but not the problem with negative floats.  That's not a scanner problem, but a parser problem.  You don't want to scan a negative number as a single token, otherwise "x-1" is scanned as (x)(-1) rather than (x) - (1).

Please report the negative number problem as a separate issue.

**Comment by CaviarChen** [comment]
Sure, will do. What about supporting float such as `1.2e-3`?  Only supporting scientific notation with positive order of magnitude such as `1.2e3` seems a bit odd.

**Comment by pschachte** [comment]
Fixed.
