### ISSUE TITLE
Incorrect int comparison

### ISSUE THREAD

**Issue by CaviarChen** [pschachte/wybe#96]
```
?res = 10 > 5
!println(res)
?res = 10 < 5
!println(res)
```
gives output:
```
false
false
```

and for this program
```
!read(?a:int)
!read(?b:int)
if { a > b ::
    !println("a > b")
| otherwise ::
    !println("a <= b")
}
```
we have:
```
> ./test 
5 10
a <= b
> ./test 
10 5
a > b
> ./test 
5 -10
a <= b
> ./test 
-10 5
a > b
```

**Comment by CaviarChen** [comment]
I think https://github.com/pschachte/wybe/commit/6536899d1e0790e2c4a25592f0ba5df4cf11ce62 only fixed the first problem but not the second one?

**Comment by pschachte** [comment]
That's a completely different bug.  Could you please open a new one for that?  I've just committed a new test case test-cases/final-dump/read_int.wybe that shows that this bug only occurs when the numbers are read from stdin.  Using the same numbers a program constants, with inlining turned off, it works fine.  Take a look at the generated LLVM code.  I'm going cross-eyed trying to see what's wrong with it.  I marked the generated code correct, because as far as I can see, it is.
